// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtinsvneSTs3cH_uvvalGDld0Ge8X7ri0',
    appId: '1:997413041644:web:c5a2753e41f300a8c6fcc9',
    messagingSenderId: '997413041644',
    projectId: 'fake-commerce-59994',
    authDomain: 'fake-commerce-59994.firebaseapp.com',
    storageBucket: 'fake-commerce-59994.firebasestorage.app',
    measurementId: 'G-BXHYV942HZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOqaDpi1ON_wyWYu_b4-iYms0aEHVfHfA',
    appId: '1:997413041644:android:883bbc50378054a6c6fcc9',
    messagingSenderId: '997413041644',
    projectId: 'fake-commerce-59994',
    storageBucket: 'fake-commerce-59994.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhNq6ddI5WsJ-vdhHGRWV7y4x6w2mOuP4',
    appId: '1:997413041644:ios:1a77e657e7b43a54c6fcc9',
    messagingSenderId: '997413041644',
    projectId: 'fake-commerce-59994',
    storageBucket: 'fake-commerce-59994.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhNq6ddI5WsJ-vdhHGRWV7y4x6w2mOuP4',
    appId: '1:997413041644:ios:1a77e657e7b43a54c6fcc9',
    messagingSenderId: '997413041644',
    projectId: 'fake-commerce-59994',
    storageBucket: 'fake-commerce-59994.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtinsvneSTs3cH_uvvalGDld0Ge8X7ri0',
    appId: '1:997413041644:web:2c5473539df8bc55c6fcc9',
    messagingSenderId: '997413041644',
    projectId: 'fake-commerce-59994',
    authDomain: 'fake-commerce-59994.firebaseapp.com',
    storageBucket: 'fake-commerce-59994.firebasestorage.app',
    measurementId: 'G-BHZH420QDQ',
  );
}
